### PR TITLE
Switched to AsyncKeyedLock library

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
This PR will improve performance and reduce memory allocations.

### CODE REVIEW

**Comment by burkenyo** [comment]
Hi @MarkCiliaVincenti, I wasn’t expecting to receive pull requests for this project, which is just my personal website. However, I’d be open to bringing this code in. Can you please explain more what this code is doing and the reasoning behind taking a new dependency? What brought about your interest in this repo?

**Comment by MarkCiliaVincenti** [comment]
Hi,

I searched for code that does similar things that my library covers and stumbled upon your project. This code will allow you to reduce allocations and improve performance though I understand that there may not be a heavy load.

**Comment by MarkCiliaVincenti** [comment]
@burkenyo ?

**Comment by burkenyo** [comment]
Hi @MarkCiliaVincenti, I have not had the time to do proper review. Unfortunately, it will be a while before I can get to it. But thanks for your interest!

**Comment by MarkCiliaVincenti** [comment]
Cheers, let me know if you need anything else.

**Comment by MarkCiliaVincenti** [comment]
> Hi @MarkCiliaVincenti, I have not had the time to do proper review. Unfortunately, it will be a while before I can get to it. But thanks for your interest!

Gentle reminder :)

**Comment by MarkCiliaVincenti** [comment]
@burkenyo  are you interested or shall I close this PR?

**Comment by MarkCiliaVincenti** [comment]
@burkenyo  please let me know

**Comment by burkenyo** [comment]
Hi, thank you for your interest, but I’m going to close this.

**Pull request closed without merging**
